### PR TITLE
(#271) fix bug: missing to check class field

### LINKED ISSUE #271: bug: class field missing check
- [x] ensure init expression has the same type as the definition
- [x] dot access must check member is what first, the current implementation only work for methods

NOTE: this blocks #257

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

File: src/codegen/mod.rs [hunk 1]
```diff
@@ -84,6 +84,11 @@ impl CodeGenerator {
                                 module.push_function(func);
                             }
                             ClassMember::Method(method) => {
+                                let mut method = method.clone();
+                                method.parameters.insert(
+                                    0,
+                                    Parameter::new("self", ParsedType::TypeName(c.name.clone())),
+                                );
```
Comment (dannypsnl) [inline src/codegen/mod.rs:91]: @YanHerChen Here transform object-orient to pure procedure-orient code. Since IR don't support concept **class**

File: src/parser/mod.rs [hunk 2]
```diff
@@ -143,11 +143,7 @@ impl Parser {
                 if self.predict_and_consume(vec![TkType::Accessor]).is_ok() {
                     members.push(ClassMember::StaticMethod(self.parse_function()?));
                 } else {
-                    let mut method = self.parse_function()?;
-                    method.parameters.insert(
-                        0,
-                        Parameter::new("self", ParsedType::TypeName(class_name.clone())),
-                    );
```
Comment (dannypsnl) [inline src/parser/mod.rs:150]: Originally, we do transform at parser. Now I remove it.

File: src/parser/tests.rs [hunk 3]
```diff
@@ -218,10 +218,7 @@ fn parse_class() {
                 ClassMember::Method(Function::new_declaration(
                     Location::from(4, 0),
                     "bar",
-                    vec![
-                        Parameter::new("self", ParsedType::type_name("Car")),
-                        Parameter::new("i", ParsedType::type_name("int"))
-                    ],
```
Comment (dannypsnl) [inline src/parser/tests.rs:224]: related to transforming, so removed.

File: src/semantic/error.rs [hunk 4]
```diff
@@ -33,6 +33,17 @@ enum SemanticErrorVariant {
     OnlyTraitCanBeSuperType { got_type: Type },
     #[error("dead code after return statement")]
     DeadCodeAfterReturnStatement,
+    #[error("redefined field `{}` in class `{}`, already defined at {}", .field_name, .class_name, .previous_definition)]
```
Comment (dannypsnl) [inline src/semantic/error.rs]: @YanHerChen Seems like I forget to change naming, it should be `member`, not `field`. Please do request changes here

File: src/semantic/mod.rs [hunk 5]
```diff
@@ -28,6 +28,19 @@ impl SemanticChecker {
...
+        }
+        for top in ast {
+            use TopAstVariant::*;
+            match &top.ast {
+                Class(c) => {
+                    let class_type = self.type_env.get_type(&c.location, &c.name)?;
+                    match class_type.typ {
+                        types::Type::ClassType { .. } => {}
+                        _ => (),
+                    }
```
Comment (dannypsnl) [inline src/semantic/mod.rs]: Here the target is to make sure each type already been emitted before others type uses it. But seems like 40 to 43 is useless code.

File: src/semantic/types.rs [hunk 6]
```diff
@@ -325,6 +351,50 @@ impl TypeInfo {
...
+            Some(v) => Ok(v),
+            None => Err(SemanticError::no_member_named(
+                location,
+                class_name,
+                name.clone(),
+            )),
+        }
+    }
+}
+
```
Comment (dannypsnl) [inline src/semantic/types.rs:397]: Here are new structures to control the class member concept in the type checker.

File: src/semantic/mod.rs (hunk 5 above)
Comment (dannypsnl) [reply src/semantic/mod.rs]: I already remove the unused code but leave the comment for your review.

File: src/semantic/error.rs (hunk 4 above)
Comment (YanHerChen) [inline src/semantic/error.rs]: please use `member`, instead of `field`.

**Review by YanHerChen — APPROVED** [review]

File: src/semantic/error.rs (hunk 4 above)
Comment (YanHerChen) [inline src/semantic/error.rs]: please use `member`, instead of `field`.

**Review by YanHerChen — CHANGES_REQUESTED** [review]
