### PR TITLE
(#247) new formatter fix bug that comment would be eliminated

### LINKED ISSUE #247: tool: `elz fmt` shouldn't remove comment
To reproduce, run `elz fmt .` at the project root, and would find `lib/prelude/prelude.elz` be reformatted.

Another important thing was we would not like to remove the newline for two elements, e.g.

```elz
class k {}

foo(): void {}
```

should be kept, but we would like to remove newlines to 1 newline, e.g.

```elz
class k {}


foo(): void {}
```

should be

```elz
class k {}

foo(): void {}
```

### PR DESCRIPTION
**Pull request by YanHerChen**

### CODE REVIEW

File: src/codegen/formatted_elz_new/tests.rs [hunk 1]
```diff
@@ -0,0 +1,227 @@
...
+  ::bar(): void {
+    return;
+  }
+}
+"
+    );
+}
+
+// helpers, must put tests before this line
+fn parse_code(code: &str) -> String {
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/tests.rs]: This is a bad name, I think ”format code” would be better.

File: src/codegen/formatted_elz_new/tests.rs [hunk 2]
```diff
@@ -0,0 +1,227 @@
...
+        "class Foo <: Bar {}
+"
+    );
+}
+
+#[test]
+fn class_multiple_super_types() {
+    let program = parse_code("class Foo<:Bar,Tool{}");
+    assert_eq!(
+        program,
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/tests.rs]: Suggested name: ”formatted code”

File: src/codegen/formatted_elz_new/mod.rs [hunk 3]
```diff
@@ -0,0 +1,184 @@
+#[cfg(test)]
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Remember remove the old module

File: src/codegen/formatted_elz_new/mod.rs [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+mod tests;
+
+fn formatted_elz(code: String) -> String {
+    let mut indent = 0i32;
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: ### Handling indent

count integer to record the indent, e.q.
```
class foo{
    fn function1(){
    }
}
```
indent is 2.

File: src/codegen/formatted_elz_new/mod.rs [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+    let mut comment_line = false;
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: if read comment line, then comment_line is true

File: src/codegen/formatted_elz_new/mod.rs [hunk 6]
```diff
@@ -0,0 +1,184 @@
...
+                        else {
+                            s.push_str(code_to_char[i]);
+                        }
+                    }
+                }
+            }
+        }
+        i += 1;
+    }
+    println!("{}", s);
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Don't print out the result! This is not expected behavior. Also, not a good debug habit. Try debugger in future.

File: src/codegen/formatted_elz_new/mod.rs [hunk 7]
```diff
@@ -0,0 +1,184 @@
...
+                        past_symbol = false;
+                    } else {
+                        s.push_str("{");
+                        s.push_str("\n");
+                        s.push_str(add_tab(indent).as_str());
+                    }
+                }
+                //delete double blank
+                "}" => {
+                    indent -= 1;
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Consider the ”state function” trick.

File: src/codegen/formatted_elz_new/mod.rs [hunk 8]
```diff
@@ -0,0 +1,184 @@
...
+                s.push_str("\n");
+                s.push_str(add_tab(indent).as_str());
+                comment_line = false;
+                i += 1;
+            } else{                
+                s.push_str(code_to_char[i]);
+            }
+        } else {
+            match code_to_char[i] {
+                //{ } ; need to add newline
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Comment should keep one space like

// ...

Not

//...

File: src/codegen/formatted_elz_new/mod.rs [hunk 9]
```diff
@@ -0,0 +1,184 @@
+#[cfg(test)]
+mod tests;
+
+fn formatted_elz(code: String) -> String {
+    let mut indent = 0i32;
+    let mut comment_line = false;
+    let mut semicolon_symbol = false;
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: if read `;` , then semicolon_symbol is true, the symbol `;` means end of line, and need to set newline.

File: src/codegen/formatted_elz_new/mod.rs [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+    let mut past_symbol = false;
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: past_symbol handling the situation like:
```
Foo = Foo{x: 1};
```
symbol `{` should not newline in this situation, when formatter read `=` before `{`, then past_symbol is true

File: src/codegen/formatted_elz_new/mod.rs [hunk 11]
```diff
@@ -0,0 +1,184 @@
...
+    let mut s = String::from("");
+    let clear_multiple_blank = code.replace("  ", "").replace("\n", "\\n");
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: Formatter replace double blank in first time, to clear multi-blank.

File: src/codegen/formatted_elz_new/mod.rs [hunk 12]
```diff
@@ -0,0 +1,184 @@
...
+                }
+            }
+        }
+        i += 1;
+    }
+    println!("{}", s);
+    s
+}
+
+fn add_tab(tab: i32) -> String {
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Add indent?

File: src/codegen/formatted_elz_new/mod.rs [hunk 13]
```diff
@@ -0,0 +1,184 @@
...
+    while i < code_to_char.len() {
+        if comment_line {
+            if code_to_char[i] == "\\" && code_to_char[i + 1] == "n" {
+                s.push_str("\n");
+                s.push_str(add_tab(indent).as_str());
+                comment_line = false;
+                i += 1;
+            } else{                
+                s.push_str(code_to_char[i]);
+            }
```
Comment (YanHerChen) [inline src/codegen/formatted_elz_new/mod.rs]: if read comment line, formatter will ignore until meet `\n`.

File: src/codegen/formatted_elz_new/mod.rs [hunk 14]
```diff
@@ -0,0 +1,184 @@
...
+    }
+    s.push_str(c);
+    if next != " " {
+        s.push_str(" ");
+    }
+    s
+}
+
+fn check_symbol_behind_space(symbol: &str) -> bool {
+    let mut b = false;
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Don't do this, return value directly.

For example

if symbol == a { true }
if...
if...
else { false }

**Review by dannypsnl — CHANGES_REQUESTED** [review]

File: src/codegen/formatted_elz_new/tests.rs (hunk 1 above)
Comment (YanHerChen) [reply src/codegen/formatted_elz_new/tests.rs]: I agree.

File: src/codegen/formatted_elz_new/tests.rs [hunk 15]
```diff
@@ -0,0 +1,227 @@
+use super::formatted_elz;
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/tests.rs]: How about ”use super::*;” to avoid any changes about this line?

File: src/codegen/formatted_elz_new/mod.rs (hunk 11 above)
Comment (dannypsnl) [reply src/codegen/formatted_elz_new/mod.rs]: Have to notice this would take 2n to deal this, n is code size.

File: src/codegen/formatted_elz_new/mod.rs [hunk 16]
```diff
@@ -0,0 +1,183 @@
+mod tests;
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: I say remove old formatter module, not metadata for rust compiler. Crate test attr helps rust compiler know mod tests is testing module. Please at least run cargo test before push any commits.

File: src/codegen/formatted_elz_new/mod.rs [hunk 17]
```diff
@@ -0,0 +1,183 @@
...
+    let mut indent = 0i32;
+    let mut comment_line = false;
+    let mut semicolon_symbol = false;
+    let mut past_symbol = false;
+    let mut s = String::from("");
+    let clear_multiple_blank = code.replace("  ", "").replace("\n", "\\n");
+    let code_to_char: Vec<&str> = clear_multiple_blank.split("").collect();
+
+    let mut i = 0;
+    while i < code_to_char.len() {
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/mod.rs]: Try .iter().enumerate()

File: src/codegen/formatted_elz_new/tests.rs [hunk 18]
```diff
@@ -0,0 +1,227 @@
...
+}
+"
+    );
+}
+
+// helpers, must put tests before this line
+fn format_code(code: &str) -> String {
+    let s = formatted_elz(code.to_string());
+    s
+}
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/tests.rs]: EOF, please ensure you're using formatter in your developing environment.

File: src/codegen/formatted_elz_new/tests.rs [hunk 19]
```diff
@@ -0,0 +1,227 @@
...
+        formatted_code,
+        "foo(): void {
+  x: int = 1;
+}
+"
+    );
+}
+
+#[test]
+fn function_call_in_function() {
```
Comment (dannypsnl) [inline src/codegen/formatted_elz_new/tests.rs]: I don't think we need this. But can test ”if” in function to ensure nested block would work.
Also can test comment in function.

**Review by dannypsnl — CHANGES_REQUESTED** [review]

File: src/codegen/formatted_elz/mod.rs [hunk 20]
```diff
@@ -1,354 +1,188 @@
...
-                    .into_iter()
-                    .map(|(field_name, field_init)| {
-                        FormatFieldInit(field_name.clone(), field_init.clone())
-                    })
-                    .collect();
-                concat_with_separator(&mut s, &fields, ", ", level);
-                s.push_str("}");
-                s
-            }
+fn add_indent(tab: i32) -> String {
```
Comment (dannypsnl) [inline src/codegen/formatted_elz/mod.rs]: Not tab, how about level?

File: src/codegen/formatted_elz/mod.rs [hunk 21]
```diff
@@ -1,354 +1,188 @@
...
-                            || "".to_string(),
-                            |expr| format!(" {}", expr.formatted_elz(level)),
-                        )
-                        .as_str(),
-                );
-                s.push_str(";");
-                s
+        } else {
+            match code_to_char[i] {
+                //{ } ; need to add newline
```
Comment (dannypsnl) [inline src/codegen/formatted_elz/mod.rs]: // { }

NOT

//{ }

Comment (dannypsnl) [reply src/codegen/formatted_elz/mod.rs]: Please fix all comments like that

File: src/codegen/formatted_elz/mod.rs [hunk 22]
```diff
@@ -1,354 +1,188 @@
...
-        let elem_str = elem.formatted_elz(level);
-        s.push_str(elem_str.as_str());
-        if index < vector.len() - 1 {
-            if elem_str != "".to_string() {
-                s.push_str(separator);
-            }
-        }
+fn check_symbol_behind_space(symbol: &str) -> bool {
+    if symbol == ";" {
+        return true;
```
Comment (dannypsnl) [inline src/codegen/formatted_elz/mod.rs]: In Rust, an exhaust if-else block doesn't need a return keyword.

You can use {true} to get same result.

File: src/codegen/formatted_elz/tests.rs [hunk 23]
```diff
@@ -122,19 +123,102 @@ fn nested_block() {
...
+
 // helpers, must put tests before this line
-fn parse_code(code: &'static str) -> FormatTopAstList {
-    let program = match Parser::parse_program("", code) {
-        Ok(program) => program,
-        Err(err) => panic!("{}", err),
-    };
-    FormatTopAstList(program)
+fn format_code(code: &str) -> String {
+    let s = formatted_elz(code.to_string());
```
Comment (dannypsnl) [inline src/codegen/formatted_elz/tests.rs]: I don't think we need to wrap ”formatted_elz.”

Directly call it would be better.

And why not name it ”format_code”? Notice the original name is because it belongs to AST. And the mod also needs a new name, how about ”formatter”?

**Review by dannypsnl — CHANGES_REQUESTED** [review]

File: src/cmd/fmt.rs [hunk 24]
```diff
@@ -1,4 +1,4 @@
-use crate::codegen::formatted_elz::formatted_elz;
+use crate::codegen::formatted_elz::formatter;
```
Comment (dannypsnl) [inline src/cmd/fmt.rs]: You didn't read it correctly. Rename mod to formatter, not function. Rename function to format_elz.

File: src/cmd/fmt.rs [hunk 25]
```diff
@@ -34,8 +33,7 @@ fn handle_dir(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
 fn handle_entry(file_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
     if file_path.extension() == Some(OsStr::new("elz")) {
         let code = std::fs::read_to_string(file_path)?;
-        let program = Parser::parse_program(file_path.to_string_lossy().to_string(), code)?;
-        let result = FormatTopAstList(program).formatted_elz(DEFAULT_LEVEL);
+        let result = formatter(code.to_string());
```
Comment (dannypsnl) [inline src/cmd/fmt.rs]: Don't you feel formatter as function name is weird?

**Review by dannypsnl — CHANGES_REQUESTED** [review]

**Review by dannypsnl — DISMISSED** [review]

**Review by dannypsnl — APPROVED** [review]
